<?php

namespace Shop\CatalogBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Shop\CatalogBundle\Entity\Product;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function findLastImages(Product $products, $limit = 20){
        $qry = $this->createQueryBuilder('c');
        $qry->where('c.products = :products');
        $qry->setParameter('products', $products);
        $qry->setMaxResults($limit);
        $qry->orderBy('c.id', 'DESC');
        return $qry->getQuery()->getResult();
    }



    /*public function findImages(Product $products, $pager = 1, $limit = 10 ){
        $qry = $this->createQueryBuilder('c');
        $qry->where('c.products = :products')->setParameter('products', $products);
        $qry->setMaxResults($limit);
        $qry->setFirstResult(($limit * $pager) - $limit);//10*1 = 10 - 10 = 0
        return $qry->getQuery()->getResult();
    }

    public function countImages(Product $products){
        $qry = $this->createQueryBuilder('c')->select('count(c.id)');
        $qry->where('c.products = :products')->setParameter('products', $products);
        $result = $qry->getQuery()->getOneOrNullResult();
        return $result ? array_shift($result) : 0;
    }*/
}
